version: "3.4"
services:

 servidor_web:
    build: ServidorWeb
    network_mode: "host"

 basedatos_tarea6:
    image: mysql:5
    environment:
      MYSQL_DATABASE: 'tarea6'
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
     - "3309:3306"
    expose:
     - '3309'
    volumes:
     - db_tarea6:/var/lib/mysql
volumes:
  db_tarea6: